export const customBackgrounds = [
  { type: 'bubbles', img: '/backgrounds/bubbles.png', title: 'Bubbles' },
  { type: 'fire', img: '/backgrounds/fire.png', title: 'Fire' },
  { type: 'clouds', img: '/backgrounds/clouds.png', title: 'Clouds' },
  { type: 'forest trail', img: '/backgrounds/forestTrail.jpg', title: 'Forest Trail' },
  { type: 'space', img: '/backgrounds/space.png', title: 'Space' },
  { type: 'mountains', img: '/backgrounds/mountains.png', title: 'Mountains' },
  { type: 'math', img: '/backgrounds/math.jpg', title: 'Math' },
  { type: 'sport', img: '/backgrounds/basketballcourt.jpg', title: 'Basketball Court' },
  { type: 'dark road', img: '/backgrounds/darkroadbetweenmountainsatnight.jpg', title: 'Dark Road' },
  { type: 'dog', img: '/backgrounds/dogpeekingup.jpg', title: 'Dog Peeking Up' },
  { type: 'shark', img: '/backgrounds/shark.jpg', title: 'Shark' },
  { type: 'lion', img: '/backgrounds/lion.jpg', title: 'Lion' },
  { type: 'giraffe', img: '/backgrounds/giraffe.jpg', title: 'Giraffe' },
  { type: 'futuristic city', img: '/backgrounds/futuristiccity.jpg', title: 'Futuristic City' },
  { type: 'spaceship', img: '/backgrounds/spaceship.webp', title: 'Spaceship' },
  { type: 'ufo', img: '/backgrounds/ufo.jpg', title: 'UFO' },
  { type: 'alien', img: '/backgrounds/alien.jpg', title: 'Alien' },
  // Add more as needed
];