// filepath: c:\Dev\EmojiCreator\emoji-creator\src\constants\galleryImages.js
export const galleryImages = [
  { src: '/gallery/Taken.jpg', label: 'I will find you, and I will kill you' },
  { src: '/gallery/AlienGod.jpg', label: 'Alien God looking over his minions' },
  { src: 'gallery/ChangeMyMind.png', label: 'Change my mind...' },
  { src: 'gallery/chooseredbutton.png', label: 'Choose red button' },
  { src: 'gallery/deathknocking.png', label: 'Death knocking on the door' },
  { src: 'gallery/jim-carrey-alrighty-then.jpg', label: 'Jim Carrey "Allllllrighty then"' },
  { src: 'gallery/jim-carrey-did-someone-say.jpg', label: 'Jim Carrey "Did someone say ..."' },
  { src: 'gallery/jim-carrey-duh.jpg', label: 'Jim Carrey "Duh"' },
  { src: 'gallery/jim-carrey-laughing.jpg', label: 'Jim Carrey laughing' },
  { src: 'gallery/girlburninghouse.png', label: 'Girl burning house' },
  { src: 'gallery/girleww.jpg', label: 'Ewwww' },
  { src: 'gallery/secrets.jpg', label: 'Gossip' },
  { src: 'gallery/goodfellaslaugh.jpg', label: 'Goodfellas laugh' },
  { src: 'gallery/jokerdancing.jpg', label: 'Joker dancing' },
  { src: 'gallery/kramer-coffee-smirk.jpg', label: 'Kramer coffee smirk' },
  { src: 'gallery/kramer-come-on.jpg', label: 'Kramer "Come on!"' },
  { src: 'gallery/Leonardo-Dicaprio-Cheers.jpg', label: 'Leonardo DiCaprio Cheers' },
  { src: 'gallery/leonardo-dicaprio-laughing.jpg', label: 'Leonardo DiCaprio laughing' },
  { src: 'gallery/leonardo-dicaprio-pointing.webp', label: 'Leonardo DiCaprio pointing' },
  { src: 'gallery/michaeljacksonpopcorn.png', label: 'Michael Jackson "this is getting good"' },
  { src: 'gallery/obama.png', label: 'Obama awarding himself' },
  { src: 'gallery/obamagaypride.jpg', label: 'Obama gay pride' },
  { src: 'gallery/sideeye.png', label: 'Side eye' },
  { src: 'gallery/piratesrunningfrom.png', label: '"oh no" - in trouble' },
  { src: 'gallery/spidermanpointing.jpg', label: 'You did it, no you did it' },
  { src: 'gallery/stadiumangry.jpg', label: 'Angry fan' },
  { src: 'gallery/sweating.jpg', label: 'Sweating nervously' },
  { src: 'gallery/that-would-be-great.webp', label: 'That would be great' },
  { src: 'gallery/theexpert.jpg', label: 'The expert' },
  { src: 'gallery/theofficeideaboard.jpg', label: 'The Office idea board' },
  { src: 'gallery/homerbackingintobushes.jpg', label: 'Sneaking away' },
  { src: 'gallery/robert-downey-jr-eyeroll.jpg', label: 'Robert Downey Jr. eye roll' },
  { src: 'gallery/smartthinker.jpg', label: 'Smart' },
  { src: 'gallery/tony-stark-relief.jpg', label: 'Tony Stark what a relief' },
  { src: 'gallery/wandavisionwinkingeye.jpg', label: 'Wanda Vision winking eye' },
  { src: 'gallery/onedoesnotsimply.jpg', label: 'One does not simply...' },
  { src: 'gallery/willsmithslap.JPG', label: 'Will Smith slap' },
  { src: 'gallery/womanyellingat.jpg', label: 'Woman yelling at ...' },
  // Add more image paths
];