/**
 * List of common gallery images for meme/emoji creation.
 * Each image has a src (path) and a label for display.
 */
export const galleryImages = [
  { type: 'miscellaneous', src: '/gallery/Taken.jpg', label: 'I will find you, and I will kill you' },
  { type: 'miscellaneous', src: '/gallery/AlienGod.jpg', label: 'Alien God looking over his minions' },
  { type: 'debate', src: '/gallery/ChangeMyMind.png', label: 'Change my mind...' },
  { type: 'miscellaneous', src: '/gallery/chooseredbutton.png', label: 'Choose red button' },
  { type: 'death', src: '/gallery/deathknocking.png', label: 'Death knocking on the door' },
  { type: 'miscellaneous', src: '/gallery/jim-carrey-alrighty-then.jpg', label: 'Jim Carrey "Allllllrighty then"' },
  { type: 'miscellaneous', src: '/gallery/jim-carrey-did-someone-say.jpg', label: 'Jim Carrey "Did someone say ..."' },
  { type: 'duh', src: '/gallery/jim-carrey-duh.jpg', label: 'Jim Carrey "Duh"' },
  { type: 'laughing', src: '/gallery/jim-carrey-laughing.jpg', label: 'Jim Carrey laughing' },
  { type: 'miscellaneous', src: '/gallery/girlburninghouse.png', label: 'Girl burning house' },
  { type: 'ewwww', src: '/gallery/girleww.jpg', label: 'Ewwww' },
  { type: 'miscellaneous', src: '/gallery/secrets.jpg', label: 'Gossip' },
  { type: 'laughing', src: '/gallery/goodfellaslaugh.jpg', label: 'Goodfellas laugh' },
  { type: 'love', src: '/gallery/heart-sun.jpg', label: 'Heart Sun' },
  { type: 'happy', src: '/gallery/jokerdancing.jpg', label: 'Joker dancing' },
  { type: 'miscellaneous', src: '/gallery/kramer-coffee-smirk.jpg', label: 'Kramer coffee smirk' },
  { type: 'miscellaneous', src: '/gallery/kramer-come-on.jpg', label: 'Kramer "Come on!"' },
  { type: 'love', src: '/gallery/kermit-love.jpg', label: 'Kermit the Frog love' },
  { type: 'cheers', src: '/gallery/Leonardo-Dicaprio-Cheers.jpg', label: 'Leonardo DiCaprio Cheers' },
  { type: 'laughing', src: '/gallery/leonardo-dicaprio-laughing.jpg', label: 'Leonardo DiCaprio laughing' },
  { type: 'miscellaneous', src: '/gallery/leonardo-dicaprio-pointing.webp', label: 'Leonardo DiCaprio pointing' },
  { type: 'love', src: '/gallery/love.jpg', label: 'Love' },
  { type: 'movie', src: '/gallery/michaeljacksonpopcorn.png', label: 'Michael Jackson "this is getting good"' },
  { type: 'miscellaneous', src: '/gallery/obama.png', label: 'Obama awarding himself' },
  { type: 'miscellaneous', src: '/gallery/obamagaypride.jpg', label: 'Obama gay pride' },
  { type: 'sideeye', src: '/gallery/sideeye.png', label: 'Side eye' },
  { type: 'miscellaneous', src: '/gallery/piratesrunningfrom.png', label: '"oh no" - in trouble' },
  { type: 'miscellaneous', src: '/gallery/spidermanpointing.jpg', label: 'You did it, no you did it' },
  { type: 'angry', src: '/gallery/stadiumangry.jpg', label: 'Angry fan' },
  { type: 'nervous', src: '/gallery/sweating.jpg', label: 'Sweating nervously' },
  { type: 'miscellaneous', src: '/gallery/that-would-be-great.webp', label: 'That would be great' },
  { type: 'miscellaneous', src: '/gallery/theexpert.jpg', label: 'The expert' },
  { type: 'idea', src: '/gallery/theofficeideaboard.jpg', label: 'The Office idea board' },
  { type: 'miscellaneous', src: '/gallery/homerbackingintobushes.jpg', label: 'Sneaking away' },
  { type: 'eyeroll', src: '/gallery/robert-downey-jr-eyeroll.jpg', label: 'Robert Downey Jr. eye roll' },
  { type: 'smart', src: '/gallery/smartthinker.jpg', label: 'Smart' },
  { type: 'relief', src: '/gallery/tony-stark-relief.jpg', label: 'Tony Stark what a relief' },
  { type: 'miscellaneous', src: '/gallery/wandavisionwinkingeye.jpg', label: 'Wanda Vision winking eye' },
  { type: 'miscellaneous', src: '/gallery/onedoesnotsimply.jpg', label: 'One does not simply...' },
  { type: 'miscellaneous', src: '/gallery/willsmithslap.JPG', label: 'Will Smith slap' },
  { type: 'miscellaneous', src: '/gallery/womanyellingat.jpg', label: 'Woman yelling at ...' },
  // Add more image paths as needed
];